/*
 * test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// PatchUsersUserId - Update User Information
func PatchUsersUserId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
