/*
 * test
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetUsersUserId - Get User Info by User ID
func GetUsersUserId(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PostUser - Create New User
func PostUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
